# _config.yml

# Basic site settings
title: "My Awesome Blog"
description: "A space where I share my thoughts and ideas."
url: "https://tranbaohieu.github.io"

# Theme settings
theme: "minimal"
# plugins:
#   - jekyll-remote-theme
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-seo-tag
#   - jekyll-feed
#   - jekyll-archives
#   - jekyll-toc


# Social media links
social_links:
  github: "https://github.com/tranbaohieu"
  twitter: "https://twitter.com/your-username"

# Site logo (upload a logo image to the assets folder and reference it here)
logo: "/assets/images/logo.png"
paginate: 5
paginate_path: "/blog/page:num"
